"""Company Module

Revision ID: 9dd991c05b4e
Revises: 6111a002f46e
Create Date: 2026-07-13 05:14:44.513058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd991c05b4e'
down_revision: Union[str, Sequence[str], None] = '6111a002f46e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('industry', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('business_type', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('currency', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('tax_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('registration_number', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('logo', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('companies_slug_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'])
    op.drop_column('companies', 'slug')
    op.drop_column('companies', 'name')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('companies', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.create_unique_constraint(op.f('companies_slug_key'), 'companies', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'owner_id')
    op.drop_column('companies', 'logo')
    op.drop_column('companies', 'registration_number')
    op.drop_column('companies', 'tax_number')
    op.drop_column('companies', 'language')
    op.drop_column('companies', 'timezone')
    op.drop_column('companies', 'currency')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'business_type')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'legal_name')
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###
