"""Add updated marketing models

Revision ID: ad10439d9399
Revises: 11aa090c055d
Create Date: 2026-07-15 04:24:50.597189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad10439d9399'
down_revision: Union[str, Sequence[str], None] = '11aa090c055d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_automation_rules_created_at'), 'automation_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_rules_deleted_at'), 'automation_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_automation_rules_name'), 'automation_rules', ['name'], unique=False)
    op.create_index(op.f('ix_automation_rules_organization_id'), 'automation_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automation_rules_status'), 'automation_rules', ['status'], unique=False)
    op.create_table('campaign_audiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_audiences_created_at'), 'campaign_audiences', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_deleted_at'), 'campaign_audiences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_name'), 'campaign_audiences', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_organization_id'), 'campaign_audiences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_audiences_status'), 'campaign_audiences', ['status'], unique=False)
    op.create_table('campaign_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_members_created_at'), 'campaign_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_members_deleted_at'), 'campaign_members', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_members_name'), 'campaign_members', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_members_organization_id'), 'campaign_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_members_status'), 'campaign_members', ['status'], unique=False)
    op.create_table('campaign_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_metrics_created_at'), 'campaign_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_deleted_at'), 'campaign_metrics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_name'), 'campaign_metrics', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_organization_id'), 'campaign_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_status'), 'campaign_metrics', ['status'], unique=False)
    op.create_table('campaign_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_schedules_created_at'), 'campaign_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_schedules_deleted_at'), 'campaign_schedules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_schedules_name'), 'campaign_schedules', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_schedules_organization_id'), 'campaign_schedules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_schedules_status'), 'campaign_schedules', ['status'], unique=False)
    op.create_table('campaign_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_segments_created_at'), 'campaign_segments', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_segments_deleted_at'), 'campaign_segments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_segments_name'), 'campaign_segments', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_segments_organization_id'), 'campaign_segments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_segments_status'), 'campaign_segments', ['status'], unique=False)
    op.create_table('campaign_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_templates_created_at'), 'campaign_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_templates_deleted_at'), 'campaign_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_templates_name'), 'campaign_templates', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_templates_organization_id'), 'campaign_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_templates_status'), 'campaign_templates', ['status'], unique=False)
    op.create_table('campaign_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_campaign_workflows_created_at'), 'campaign_workflows', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaign_workflows_deleted_at'), 'campaign_workflows', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaign_workflows_name'), 'campaign_workflows', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_workflows_organization_id'), 'campaign_workflows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaign_workflows_status'), 'campaign_workflows', ['status'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_index(op.f('ix_coupons_created_at'), 'coupons', ['created_at'], unique=False)
    op.create_index(op.f('ix_coupons_deleted_at'), 'coupons', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_coupons_name'), 'coupons', ['name'], unique=False)
    op.create_index(op.f('ix_coupons_organization_id'), 'coupons', ['organization_id'], unique=False)
    op.create_index(op.f('ix_coupons_status'), 'coupons', ['status'], unique=False)
    op.create_table('customer_journeies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_customer_journeies_created_at'), 'customer_journeies', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_journeies_deleted_at'), 'customer_journeies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_customer_journeies_name'), 'customer_journeies', ['name'], unique=False)
    op.create_index(op.f('ix_customer_journeies_organization_id'), 'customer_journeies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customer_journeies_status'), 'customer_journeies', ['status'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_email_templates_created_at'), 'email_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_templates_deleted_at'), 'email_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_templates_name'), 'email_templates', ['name'], unique=False)
    op.create_index(op.f('ix_email_templates_organization_id'), 'email_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_email_templates_status'), 'email_templates', ['status'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_form_submissions_created_at'), 'form_submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_submissions_deleted_at'), 'form_submissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_submissions_name'), 'form_submissions', ['name'], unique=False)
    op.create_index(op.f('ix_form_submissions_organization_id'), 'form_submissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_status'), 'form_submissions', ['status'], unique=False)
    op.create_table('landing_page_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_landing_page_forms_created_at'), 'landing_page_forms', ['created_at'], unique=False)
    op.create_index(op.f('ix_landing_page_forms_deleted_at'), 'landing_page_forms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_landing_page_forms_name'), 'landing_page_forms', ['name'], unique=False)
    op.create_index(op.f('ix_landing_page_forms_organization_id'), 'landing_page_forms', ['organization_id'], unique=False)
    op.create_index(op.f('ix_landing_page_forms_status'), 'landing_page_forms', ['status'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_landing_pages_created_at'), 'landing_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_landing_pages_deleted_at'), 'landing_pages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_landing_pages_name'), 'landing_pages', ['name'], unique=False)
    op.create_index(op.f('ix_landing_pages_organization_id'), 'landing_pages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_status'), 'landing_pages', ['status'], unique=False)
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_loyalty_accounts_created_at'), 'loyalty_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_deleted_at'), 'loyalty_accounts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_name'), 'loyalty_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_organization_id'), 'loyalty_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_loyalty_accounts_status'), 'loyalty_accounts', ['status'], unique=False)
    op.create_table('loyalty_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_loyalty_programs_created_at'), 'loyalty_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_deleted_at'), 'loyalty_programs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_name'), 'loyalty_programs', ['name'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_organization_id'), 'loyalty_programs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_loyalty_programs_status'), 'loyalty_programs', ['status'], unique=False)
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_loyalty_transactions_created_at'), 'loyalty_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_deleted_at'), 'loyalty_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_name'), 'loyalty_transactions', ['name'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_organization_id'), 'loyalty_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_status'), 'loyalty_transactions', ['status'], unique=False)
    op.create_table('marketing_analyticss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_marketing_analyticss_created_at'), 'marketing_analyticss', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketing_analyticss_deleted_at'), 'marketing_analyticss', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_marketing_analyticss_name'), 'marketing_analyticss', ['name'], unique=False)
    op.create_index(op.f('ix_marketing_analyticss_organization_id'), 'marketing_analyticss', ['organization_id'], unique=False)
    op.create_index(op.f('ix_marketing_analyticss_status'), 'marketing_analyticss', ['status'], unique=False)
    op.create_table('marketing_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_marketing_campaigns_created_at'), 'marketing_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_deleted_at'), 'marketing_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_name'), 'marketing_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_organization_id'), 'marketing_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_marketing_campaigns_status'), 'marketing_campaigns', ['status'], unique=False)
    op.create_table('marketing_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_marketing_tags_created_at'), 'marketing_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketing_tags_deleted_at'), 'marketing_tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_marketing_tags_name'), 'marketing_tags', ['name'], unique=False)
    op.create_index(op.f('ix_marketing_tags_organization_id'), 'marketing_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_marketing_tags_status'), 'marketing_tags', ['status'], unique=False)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_newsletters_created_at'), 'newsletters', ['created_at'], unique=False)
    op.create_index(op.f('ix_newsletters_deleted_at'), 'newsletters', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_newsletters_name'), 'newsletters', ['name'], unique=False)
    op.create_index(op.f('ix_newsletters_organization_id'), 'newsletters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_newsletters_status'), 'newsletters', ['status'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_promotions_created_at'), 'promotions', ['created_at'], unique=False)
    op.create_index(op.f('ix_promotions_deleted_at'), 'promotions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_promotions_name'), 'promotions', ['name'], unique=False)
    op.create_index(op.f('ix_promotions_organization_id'), 'promotions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_promotions_status'), 'promotions', ['status'], unique=False)
    op.create_table('push_notification_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_push_notification_campaigns_created_at'), 'push_notification_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_push_notification_campaigns_deleted_at'), 'push_notification_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_push_notification_campaigns_name'), 'push_notification_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_push_notification_campaigns_organization_id'), 'push_notification_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_push_notification_campaigns_status'), 'push_notification_campaigns', ['status'], unique=False)
    op.create_table('referral_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_referral_programs_created_at'), 'referral_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_programs_deleted_at'), 'referral_programs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_referral_programs_name'), 'referral_programs', ['name'], unique=False)
    op.create_index(op.f('ix_referral_programs_organization_id'), 'referral_programs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referral_programs_status'), 'referral_programs', ['status'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_deleted_at'), 'referrals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_referrals_name'), 'referrals', ['name'], unique=False)
    op.create_index(op.f('ix_referrals_organization_id'), 'referrals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('s_m_s_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_s_m_s_campaigns_created_at'), 's_m_s_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_s_m_s_campaigns_deleted_at'), 's_m_s_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_s_m_s_campaigns_name'), 's_m_s_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_s_m_s_campaigns_organization_id'), 's_m_s_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_s_m_s_campaigns_status'), 's_m_s_campaigns', ['status'], unique=False)
    op.create_table('social_media_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_social_media_campaigns_created_at'), 'social_media_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_media_campaigns_deleted_at'), 'social_media_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_social_media_campaigns_name'), 'social_media_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_social_media_campaigns_organization_id'), 'social_media_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_social_media_campaigns_status'), 'social_media_campaigns', ['status'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_subscribers_created_at'), 'subscribers', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscribers_deleted_at'), 'subscribers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscribers_name'), 'subscribers', ['name'], unique=False)
    op.create_index(op.f('ix_subscribers_organization_id'), 'subscribers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscribers_status'), 'subscribers', ['status'], unique=False)
    op.create_table('subscription_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_subscription_preferences_created_at'), 'subscription_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_preferences_deleted_at'), 'subscription_preferences', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscription_preferences_name'), 'subscription_preferences', ['name'], unique=False)
    op.create_index(op.f('ix_subscription_preferences_organization_id'), 'subscription_preferences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_subscription_preferences_status'), 'subscription_preferences', ['status'], unique=False)
    op.create_table('trigger_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_trigger_events_created_at'), 'trigger_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_trigger_events_deleted_at'), 'trigger_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trigger_events_name'), 'trigger_events', ['name'], unique=False)
    op.create_index(op.f('ix_trigger_events_organization_id'), 'trigger_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_status'), 'trigger_events', ['status'], unique=False)
    op.create_table('whats_app_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_whats_app_campaigns_created_at'), 'whats_app_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_whats_app_campaigns_deleted_at'), 'whats_app_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_whats_app_campaigns_name'), 'whats_app_campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_whats_app_campaigns_organization_id'), 'whats_app_campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whats_app_campaigns_status'), 'whats_app_campaigns', ['status'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_lead_scores_created_at'), 'lead_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_scores_deleted_at'), 'lead_scores', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lead_scores_lead_id'), 'lead_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_name'), 'lead_scores', ['name'], unique=False)
    op.create_index(op.f('ix_lead_scores_organization_id'), 'lead_scores', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_status'), 'lead_scores', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_scores_status'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_organization_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_name'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_lead_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_deleted_at'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_created_at'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_whats_app_campaigns_status'), table_name='whats_app_campaigns')
    op.drop_index(op.f('ix_whats_app_campaigns_organization_id'), table_name='whats_app_campaigns')
    op.drop_index(op.f('ix_whats_app_campaigns_name'), table_name='whats_app_campaigns')
    op.drop_index(op.f('ix_whats_app_campaigns_deleted_at'), table_name='whats_app_campaigns')
    op.drop_index(op.f('ix_whats_app_campaigns_created_at'), table_name='whats_app_campaigns')
    op.drop_table('whats_app_campaigns')
    op.drop_index(op.f('ix_trigger_events_status'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_organization_id'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_name'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_deleted_at'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_created_at'), table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_index(op.f('ix_subscription_preferences_status'), table_name='subscription_preferences')
    op.drop_index(op.f('ix_subscription_preferences_organization_id'), table_name='subscription_preferences')
    op.drop_index(op.f('ix_subscription_preferences_name'), table_name='subscription_preferences')
    op.drop_index(op.f('ix_subscription_preferences_deleted_at'), table_name='subscription_preferences')
    op.drop_index(op.f('ix_subscription_preferences_created_at'), table_name='subscription_preferences')
    op.drop_table('subscription_preferences')
    op.drop_index(op.f('ix_subscribers_status'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_organization_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_name'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_deleted_at'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_created_at'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_social_media_campaigns_status'), table_name='social_media_campaigns')
    op.drop_index(op.f('ix_social_media_campaigns_organization_id'), table_name='social_media_campaigns')
    op.drop_index(op.f('ix_social_media_campaigns_name'), table_name='social_media_campaigns')
    op.drop_index(op.f('ix_social_media_campaigns_deleted_at'), table_name='social_media_campaigns')
    op.drop_index(op.f('ix_social_media_campaigns_created_at'), table_name='social_media_campaigns')
    op.drop_table('social_media_campaigns')
    op.drop_index(op.f('ix_s_m_s_campaigns_status'), table_name='s_m_s_campaigns')
    op.drop_index(op.f('ix_s_m_s_campaigns_organization_id'), table_name='s_m_s_campaigns')
    op.drop_index(op.f('ix_s_m_s_campaigns_name'), table_name='s_m_s_campaigns')
    op.drop_index(op.f('ix_s_m_s_campaigns_deleted_at'), table_name='s_m_s_campaigns')
    op.drop_index(op.f('ix_s_m_s_campaigns_created_at'), table_name='s_m_s_campaigns')
    op.drop_table('s_m_s_campaigns')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_organization_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_name'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_deleted_at'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_programs_status'), table_name='referral_programs')
    op.drop_index(op.f('ix_referral_programs_organization_id'), table_name='referral_programs')
    op.drop_index(op.f('ix_referral_programs_name'), table_name='referral_programs')
    op.drop_index(op.f('ix_referral_programs_deleted_at'), table_name='referral_programs')
    op.drop_index(op.f('ix_referral_programs_created_at'), table_name='referral_programs')
    op.drop_table('referral_programs')
    op.drop_index(op.f('ix_push_notification_campaigns_status'), table_name='push_notification_campaigns')
    op.drop_index(op.f('ix_push_notification_campaigns_organization_id'), table_name='push_notification_campaigns')
    op.drop_index(op.f('ix_push_notification_campaigns_name'), table_name='push_notification_campaigns')
    op.drop_index(op.f('ix_push_notification_campaigns_deleted_at'), table_name='push_notification_campaigns')
    op.drop_index(op.f('ix_push_notification_campaigns_created_at'), table_name='push_notification_campaigns')
    op.drop_table('push_notification_campaigns')
    op.drop_index(op.f('ix_promotions_status'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_organization_id'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_name'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_deleted_at'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_created_at'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_newsletters_status'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_organization_id'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_name'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_deleted_at'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_created_at'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_marketing_tags_status'), table_name='marketing_tags')
    op.drop_index(op.f('ix_marketing_tags_organization_id'), table_name='marketing_tags')
    op.drop_index(op.f('ix_marketing_tags_name'), table_name='marketing_tags')
    op.drop_index(op.f('ix_marketing_tags_deleted_at'), table_name='marketing_tags')
    op.drop_index(op.f('ix_marketing_tags_created_at'), table_name='marketing_tags')
    op.drop_table('marketing_tags')
    op.drop_index(op.f('ix_marketing_campaigns_status'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_organization_id'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_name'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_deleted_at'), table_name='marketing_campaigns')
    op.drop_index(op.f('ix_marketing_campaigns_created_at'), table_name='marketing_campaigns')
    op.drop_table('marketing_campaigns')
    op.drop_index(op.f('ix_marketing_analyticss_status'), table_name='marketing_analyticss')
    op.drop_index(op.f('ix_marketing_analyticss_organization_id'), table_name='marketing_analyticss')
    op.drop_index(op.f('ix_marketing_analyticss_name'), table_name='marketing_analyticss')
    op.drop_index(op.f('ix_marketing_analyticss_deleted_at'), table_name='marketing_analyticss')
    op.drop_index(op.f('ix_marketing_analyticss_created_at'), table_name='marketing_analyticss')
    op.drop_table('marketing_analyticss')
    op.drop_index(op.f('ix_loyalty_transactions_status'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_organization_id'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_name'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_deleted_at'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_created_at'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_programs_status'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_organization_id'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_name'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_deleted_at'), table_name='loyalty_programs')
    op.drop_index(op.f('ix_loyalty_programs_created_at'), table_name='loyalty_programs')
    op.drop_table('loyalty_programs')
    op.drop_index(op.f('ix_loyalty_accounts_status'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_organization_id'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_name'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_deleted_at'), table_name='loyalty_accounts')
    op.drop_index(op.f('ix_loyalty_accounts_created_at'), table_name='loyalty_accounts')
    op.drop_table('loyalty_accounts')
    op.drop_index(op.f('ix_landing_pages_status'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_organization_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_name'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_deleted_at'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_created_at'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_landing_page_forms_status'), table_name='landing_page_forms')
    op.drop_index(op.f('ix_landing_page_forms_organization_id'), table_name='landing_page_forms')
    op.drop_index(op.f('ix_landing_page_forms_name'), table_name='landing_page_forms')
    op.drop_index(op.f('ix_landing_page_forms_deleted_at'), table_name='landing_page_forms')
    op.drop_index(op.f('ix_landing_page_forms_created_at'), table_name='landing_page_forms')
    op.drop_table('landing_page_forms')
    op.drop_index(op.f('ix_form_submissions_status'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_organization_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_name'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_deleted_at'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_created_at'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_email_templates_status'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_organization_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_name'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_deleted_at'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_created_at'), table_name='email_templates')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_customer_journeies_status'), table_name='customer_journeies')
    op.drop_index(op.f('ix_customer_journeies_organization_id'), table_name='customer_journeies')
    op.drop_index(op.f('ix_customer_journeies_name'), table_name='customer_journeies')
    op.drop_index(op.f('ix_customer_journeies_deleted_at'), table_name='customer_journeies')
    op.drop_index(op.f('ix_customer_journeies_created_at'), table_name='customer_journeies')
    op.drop_table('customer_journeies')
    op.drop_index(op.f('ix_coupons_status'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_organization_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_name'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_deleted_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_created_at'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_campaign_workflows_status'), table_name='campaign_workflows')
    op.drop_index(op.f('ix_campaign_workflows_organization_id'), table_name='campaign_workflows')
    op.drop_index(op.f('ix_campaign_workflows_name'), table_name='campaign_workflows')
    op.drop_index(op.f('ix_campaign_workflows_deleted_at'), table_name='campaign_workflows')
    op.drop_index(op.f('ix_campaign_workflows_created_at'), table_name='campaign_workflows')
    op.drop_table('campaign_workflows')
    op.drop_index(op.f('ix_campaign_templates_status'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_organization_id'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_name'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_deleted_at'), table_name='campaign_templates')
    op.drop_index(op.f('ix_campaign_templates_created_at'), table_name='campaign_templates')
    op.drop_table('campaign_templates')
    op.drop_index(op.f('ix_campaign_segments_status'), table_name='campaign_segments')
    op.drop_index(op.f('ix_campaign_segments_organization_id'), table_name='campaign_segments')
    op.drop_index(op.f('ix_campaign_segments_name'), table_name='campaign_segments')
    op.drop_index(op.f('ix_campaign_segments_deleted_at'), table_name='campaign_segments')
    op.drop_index(op.f('ix_campaign_segments_created_at'), table_name='campaign_segments')
    op.drop_table('campaign_segments')
    op.drop_index(op.f('ix_campaign_schedules_status'), table_name='campaign_schedules')
    op.drop_index(op.f('ix_campaign_schedules_organization_id'), table_name='campaign_schedules')
    op.drop_index(op.f('ix_campaign_schedules_name'), table_name='campaign_schedules')
    op.drop_index(op.f('ix_campaign_schedules_deleted_at'), table_name='campaign_schedules')
    op.drop_index(op.f('ix_campaign_schedules_created_at'), table_name='campaign_schedules')
    op.drop_table('campaign_schedules')
    op.drop_index(op.f('ix_campaign_metrics_status'), table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_organization_id'), table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_name'), table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_deleted_at'), table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_created_at'), table_name='campaign_metrics')
    op.drop_table('campaign_metrics')
    op.drop_index(op.f('ix_campaign_members_status'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_organization_id'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_name'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_deleted_at'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_created_at'), table_name='campaign_members')
    op.drop_table('campaign_members')
    op.drop_index(op.f('ix_campaign_audiences_status'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_organization_id'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_name'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_deleted_at'), table_name='campaign_audiences')
    op.drop_index(op.f('ix_campaign_audiences_created_at'), table_name='campaign_audiences')
    op.drop_table('campaign_audiences')
    op.drop_index(op.f('ix_automation_rules_status'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_organization_id'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_name'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_deleted_at'), table_name='automation_rules')
    op.drop_index(op.f('ix_automation_rules_created_at'), table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
