import React, { useState, useEffect } from "react";
import { Database, Search, Table, HelpCircle, FileCheck, ShieldCheck, Cpu } from "lucide-react";

interface DBViewerProps {
  onForceReload: () => void;
  companiesCount: number;
  departmentsCount: number;
  leadsCount: number;
}

type TableKey =
  | "employees"
  | "roles"
  | "capabilities"
  | "permissions"
  | "configurations"
  | "memories"
  | "tasks"
  | "decisions"
  | "recommendations"
  | "reports"
  | "analytics"
  | "auditLogs";

export default function DBViewer({
  onForceReload,
  companiesCount,
  departmentsCount,
  leadsCount
}: DBViewerProps) {
  const [selectedTable, setSelectedTable] = useState<TableKey>("employees");
  const [dbData, setDbData] = useState<any>({});
  const [searchQuery, setSearchQuery] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchDbState();
  }, [selectedTable]);

  const fetchDbState = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/v1/workforce/debug-db");
      const json = await res.json();
      if (json.success && json.data) {
        setDbData(json.data);
      }
    } catch (e) {
      console.error("Failed to load debug db state", e);
    } finally {
      setLoading(false);
    }
  };

  const getRows = () => {
    const list = dbData[selectedTable] || [];
    if (!searchQuery.trim()) return list;
    const q = searchQuery.toLowerCase();
    return list.filter((row: any) =>
      JSON.stringify(row).toLowerCase().includes(q)
    );
  };

  const tablesMeta = [
    { id: "employees", label: "🤖 AIEmployee", desc: "Seeded profiles for the 14 AI agents, including avatar URLs, operational statuses, and salaries" },
    { id: "roles", label: "📋 AIEmployeeRole", desc: "Detailed business mandates, authority boundaries, and core operational responsibilities" },
    { id: "capabilities", label: "⚡ AIEmployeeCapability", desc: "Registered skills (e.g. Forecasting, Direct Marketing, SLA Audits) mapped to agent IDs" },
    { id: "permissions", label: "🛡️ AIEmployeePermission", desc: "SOC-2 access tokens, scopes, and target corporate department parameters" },
    { id: "configurations", label: "⚙️ AIEmployeeConfiguration", desc: "Customizable LLM settings: temperature limits, response styling, and enabled local tools" },
    { id: "memories", label: "🧠 AIEmployeeMemory", desc: "Chronological knowledge store containing both short-term context and long-term memories" },
    { id: "tasks", label: "✅ AIEmployeeTask", desc: "Current and historical task assignments including priority, status, and due dates" },
    { id: "decisions", label: "📈 AIEmployeeDecision", desc: "System-wide tracking of strategic delegation reasoning and organizational impacts" },
    { id: "recommendations", label: "💡 AIEmployeeRecommendation", desc: "Highly computed business tips and score ratings generated by analytical agents" },
    { id: "reports", label: "📄 AIEmployeeReport", desc: "Compiled Markdown executive briefings, diagnostic audits, and performance summaries" },
    { id: "analytics", label: "📊 AIEmployeeAnalytics", desc: "Dynamic KPI counts, task completions, and productivity metrics" },
    { id: "auditLogs", label: "🔒 AIEmployeeAuditLog", desc: "Corporate-grade permission validation trail logging GDPR & SOC-2 compliance checks" }
  ];

  const currentMeta = tablesMeta.find(t => t.id === selectedTable);
  const rows = getRows();

  return (
    <div className="bg-slate-900/50 border border-slate-900 rounded-2xl p-6 flex flex-col gap-6 w-full">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-900 pb-4">
        <div>
          <h2 className="font-sans font-bold text-white text-lg tracking-tight flex items-center gap-2">
            <Database className="w-5 h-5 text-cyan-400" />
            Autonomous State Table Inspector
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Browse and query Exshopi's 12 relational AI Workforce tables synchronized in memory.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              fetchDbState();
              onForceReload();
            }}
            className="bg-slate-950 border border-slate-800 hover:text-cyan-400 text-slate-300 font-semibold text-xs px-4 py-2 rounded-xl flex items-center gap-1.5 transition-colors"
          >
            Refresh State
          </button>
        </div>
      </div>

      {/* Grid selector + viewer layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Table Selector Sidebar (4 Cols) */}
        <div className="lg:col-span-3 flex flex-col gap-2 bg-slate-950/40 p-3 rounded-2xl border border-slate-900">
          <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider px-2 pb-1.5 border-b border-slate-900">
            WORKFORCE SCHEMA TABLES
          </div>
          {tablesMeta.map(tab => {
            const count = dbData[tab.id]?.length || 0;
            return (
              <button
                key={tab.id}
                onClick={() => {
                  setSelectedTable(tab.id as TableKey);
                  setSearchQuery("");
                }}
                className={`flex items-center justify-between px-3 py-2 text-xs font-semibold rounded-xl text-left transition-all ${
                  selectedTable === tab.id
                    ? "bg-cyan-600 text-white"
                    : "text-slate-400 hover:bg-slate-900 hover:text-slate-200"
                }`}
              >
                <span>{tab.label}</span>
                <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded-full font-bold ${
                  selectedTable === tab.id ? "bg-cyan-500 text-white" : "bg-slate-900 text-slate-500"
                }`}>
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {/* Rows Table Viewer (9 Cols) */}
        <div className="lg:col-span-9 flex flex-col gap-4">
          {/* Active Table Meta banner */}
          <div className="bg-slate-950 border border-slate-900 p-4 rounded-2xl flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <span className="text-white font-sans font-bold text-sm">Table: {currentMeta?.label}</span>
              <span className="bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-[9px] font-mono px-2 py-0.5 rounded font-bold">RELATIONAL</span>
            </div>
            <p className="text-xs text-slate-400 font-sans">{currentMeta?.desc}</p>
          </div>

          {/* Search bar */}
          <div className="relative">
            <Search className="w-4 h-4 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder={`Search within ${rows.length} rows...`}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl pl-9 pr-4 py-2 text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-cyan-500 transition-colors"
            />
          </div>

          {/* Core Table Render */}
          <div className="bg-slate-950/40 border border-slate-900 rounded-2xl overflow-hidden overflow-x-auto">
            {loading ? (
              <div className="py-20 text-center text-xs text-slate-500 font-sans">
                Refreshing synchronized database states...
              </div>
            ) : rows.length === 0 ? (
              <div className="py-20 text-center text-xs text-slate-600 font-sans">
                No matching records found in table.
              </div>
            ) : (
              <table className="w-full text-left border-collapse min-w-[600px]">
                <thead>
                  <tr className="border-b border-slate-900 text-slate-400 text-[10px] font-bold uppercase tracking-wider font-sans bg-slate-950">
                    <th className="py-3.5 px-4 font-mono">ID</th>
                    {Object.keys(rows[0])
                      .filter(k => k !== "id")
                      .map(key => (
                        <th key={key} className="py-3.5 px-4">{key.replace(/_/g, " ")}</th>
                      ))}
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row: any) => (
                    <tr key={row.id} className="border-b border-slate-900/60 hover:bg-slate-900/30 text-slate-300 text-xs transition-colors">
                      <td className="py-3.5 px-4 font-mono text-slate-500">#{row.id}</td>
                      {Object.keys(row)
                        .filter(k => k !== "id")
                        .map(key => {
                          const val = row[key];
                          return (
                            <td key={key} className="py-3.5 px-4 max-w-[200px] truncate">
                              {typeof val === "object" ? (
                                <span className="text-[10px] font-mono text-slate-500">{JSON.stringify(val)}</span>
                              ) : typeof val === "boolean" ? (
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${val ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" : "bg-rose-500/10 text-rose-400 border border-rose-500/20"}`}>
                                  {val ? "TRUE" : "FALSE"}
                                </span>
                              ) : key.toLowerCase().includes("salary") || key.toLowerCase().includes("budget") ? (
                                <span className="font-mono text-emerald-400 font-bold">${val?.toLocaleString()}</span>
                              ) : key === "status" ? (
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${val === "active" || val === "Completed" ? "bg-emerald-500/10 text-emerald-400" : "bg-amber-500/10 text-amber-400"}`}>
                                  {String(val).toUpperCase()}
                                </span>
                              ) : (
                                <span className="text-slate-300 font-sans">{String(val)}</span>
                              )}
                            </td>
                          );
                        })}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
